fix(#54): add named route, update view and controllers
romanzipp/Laravel-Queue-Monitor pull request #57
Opened 2021-03-03 07:15 UTC by huzaifaarain

- Updated all routes using Name Routes
- Removed `action()` and added `route()` function in views
- Removed `action()` and added `route()` function in controllers

2021-03-04 12:25 UTC, sabinico approved these changes
Reviewed and working fine in Laravel 5.8

2021-03-04 16:27 UTC, romanzipp requested changes

2021-03-04 16:27 UTC, romanzipp commented on src/Controllers/DeleteMonitorController.php
> +        return redirect()->route("romanzipp.showQueueMonitor");
```suggestion
        return redirect()->route('queue-monitor::index');
```

2021-03-04 16:27 UTC, romanzipp commented on src/Controllers/PurgeMonitorsController.php
> +        return redirect()->route('romanzipp.showQueueMonitor');
```suggestion
        return redirect()->route('queue-monitor::index');
```

2021-03-04 16:27 UTC, romanzipp commented on src/Routes/QueueMonitorRoutes.php
> +            $this->get('', '\romanzipp\QueueMonitor\Controllers\ShowQueueMonitorController')->name("romanzipp.showQueueMonitor");
```suggestion
            $this->get('', '\romanzipp\QueueMonitor\Controllers\ShowQueueMonitorController')->name('queue-monitor::index');
```

2021-03-04 16:27 UTC, romanzipp commented on src/Routes/QueueMonitorRoutes.php
> +                $this->delete('monitors/{monitor}', '\romanzipp\QueueMonitor\Controllers\DeleteMonitorController')->name("romanzipp.deleteMonitorEntry");;
```suggestion
                $this->delete('monitors/{monitor}', '\romanzipp\QueueMonitor\Controllers\DeleteMonitorController')->name('queue-monitor::destroy');
```

2021-03-04 16:27 UTC, romanzipp commented on src/Routes/QueueMonitorRoutes.php
> +                $this->delete('purge', '\romanzipp\QueueMonitor\Controllers\PurgeMonitorsController')->name("romanzipp.purgeMonitorEntries");;
```suggestion
                $this->delete('purge', '\romanzipp\QueueMonitor\Controllers\PurgeMonitorsController')->name('queue-monitor::purge');
```

2021-03-04 16:27 UTC, romanzipp commented on views/jobs.blade.php
> +                                <form action="{{ route('romanzipp.deleteMonitorEntry',[$job]) }}" method="post">
```suggestion
                                <form action="{{ route('queue-monitor::destroy', [$job]) }}" method="post">
```

2021-03-04 16:27 UTC, romanzipp commented on views/jobs.blade.php
> +            <form action="{{ route('romanzipp.purgeMonitorEntries') }}" method="post">
```suggestion
            <form action="{{ route('queue-monitor::purge') }}" method="post">
```

2021-03-04 16:28 UTC, romanzipp commented
I've made some adjustments to the route prefixes by adding `::` as prefix separator to indicate that these routes are package provided and changed the prefix to `queue-monitor`

2021-03-05 07:53 UTC, romanzipp commented
Thanks!

2021-03-05 07:53 UTC, merged